version: "3"

services:
  wordpress:
    build: ./docker/wordpress_xdebug
    image: wordpress-xdebug
    container_name: wc_korea
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "80:80"
    env_file:
      - default.env
    volumes:
      - ./docker/wordpress:/var/www/html/:delegated
      - ./docker/logs/apache2/:/var/log/apache2
      - .:/var/www/html/wp-content/plugins/korea-for-woocommerce
      - ./docker/dev-php.ini:/usr/local/etc/php/conf.d/dev-php.ini
  db:
    container_name: wc_korea_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - default.env
    volumes:
      - ./docker/data:/var/lib/mysql
  phpMyAdmin:
    container_name: wc_korea_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    env_file:
      - default.env