name: build

on:
  # Trigger the workflow on push,
  # but only for the update/ci-di branch
  push:
    branches:
      - update/ci-di
  # Trigger the workflow on pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

jobs:
  run:  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
        wp-versions: [ '5.7' ]
    name: WordPress ${{ matrix.wp-versions }} ( PHP ${{ matrix.php-versions }} )

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install npm dependencies
      run: |
        npm install

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql
        ini-values: post_max_size=256M
        coverage: none

    - name: Check PHP Version
      run: php -v

    - name: Configure wp-env
      run: |
        cat >>./.wp-env.override.json <<END
        {
          "core": "WordPress/WordPress#${{ matrix.wp-versions }}",
          "phpVersion": "${{ matrix.php-versions }}"
        }
        END

    - name: Start wp-env
      run: |
        npm run env:start

    - name: Setup wp-env
      run: npm run test:setup
      
    - name: End to End testing...
      run: npm run test:run