name: Unit tests

on:
    push:
        branches:
            - main
            - dev/1.2
    pull_request:
        branches:
            - main

jobs:
    run:
        runs-on: ubuntu-latest
        name: Unit Tests
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install npm dependencies
              run: npm install

            - name: Install composer dependencies
              run: composer install

            - name: Setup wp-env
              run: npm run env:start

            - name: Run unit tests...
              run: npm run test:unit:php
